version: '3.8'

services:
  app:
    build: .
    ports:
      - "8090:8090"
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - campaigns-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  campaigns-data:
